name: Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start containers
        run: |
          docker-compose up -d --build

      - name: Wait for containers to start
        run: sleep 30

      - name: Add entry to hosts file
        run: echo "127.0.0.1 app" | sudo tee -a /etc/hosts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Set PIPELINE_ENV variable
        run: echo "PIPELINE_ENV=1" >> $GITHUB_ENV

      - name: Run API tests
        run: pytest src/tests/tests_api.py

      - name: Run comments tests
        run: pytest src/tests/tests_comments.py

      - name: Run comments tests
        run: pytest src/tests/tests_database.py        

      - name: Stop and remove containers
        run: docker-compose down --rmi all
