version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: admin
      DB_USER: admin
      DB_PASSWORD: admin
    command: python main.py

volumes:
  db_data:
